### ISSUE TITLE
[Feature Request] Please add option in update intervals -> "manually"

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [woheller69/spritpreise#10]
Right now, there are the following options: 5, 10, 15, 30 min. To go easy on resources of the server and prevent battery drain in the phone, I would like to have an option to only manually refresh data.

Thank you.

**Comment by woheller69** [comment]
If you are not using the widget as long as you do not open the app there is no update in backgound. Only if you open the app and data is older than x data will be updated for the city you are looking at.

**Comment by klawdhfzasjhaa** [comment]
Thx for the explanation. Then maybe rename the item from "Update Interval" to "Update Interval (Widget only)" or something.
