### ISSUE TITLE
Enhancement: Pull-to-refresh gas prices

### ISSUE THREAD

**Issue by mueller-ma** [woheller69/spritpreise#14]

**Comment by woheller69** [comment]
this is implemented

**Comment by mueller-ma** [comment]
I'm using version 1.5 from F-Droid, but I cannot pull-to-refresh in `CityGasPricesActivity`.

**Comment by woheller69** [comment]
it works when you pull the Last Update area

**Comment by woheller69** [comment]
pull down on the stations list to refresh had some problems because it is a vertical recyclerview if I remember correctly.

**Comment by mueller-ma** [comment]
> it works when you pull the Last Update area

I cannot make it working on my device or there's at least no visual indicator.

> pull down on the stations list to refresh had some problems because it is a vertical recyclerview if I remember correctly.

In other apps I used `SwipeRefreshLayout` which also working with vertical recyclerview: https://developer.android.com/develop/ui/views/touch-and-input/swipe/add-swipe-interface

**Comment by woheller69** [comment]
Please try. Remove .zip and install (uninstall F-droid version first)

[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/9488705/app-release.apk.zip)

**Comment by mueller-ma** [comment]
Can you push the code to a branch? I'll build it myself then, so I don't have to reinstall.

**Comment by woheller69** [comment]
it is on the main branch

**Comment by mueller-ma** [comment]
Did you try using `SwipeRefreshLayout`? I would add a visual clue that swipe-to-refresh is supported here.

**Comment by woheller69** [comment]
no, I did not try that yet

**Comment by woheller69** [comment]
fixed in V1.6
