### ISSUE TITLE
Spritpreise possible on Wear OS? 

### ISSUE THREAD

**Issue by deejay73** [woheller69/spritpreise#18]
Not a issue, but... 
will it be possible to get a version for Wear OS on Samsung Galaxy Watch 4 classic? I think, the app will work fine, but the button to add any location is not visible on the screen.

Auf deutsch: Hallo, ich habe seit kurzem eine Samsung Galaxy Watch 4 classic mit 46mm Display. Die App habe ich von F-Droid heruntergeladen und per adb auf die Uhr übertragen. Die App scheint ansich zu funktionieren, jedoch kann ich keine Standorte manuell hinzufügen. Der Grund: Der Button, um Standorte hinzuzufügen, befindet sich rechts unten, außerhalb des Bildschirmes! Ist es möglich, eine für Smartwatches angepasste Version zu erhalten?

Gruß deejay73

**Comment by woheller69** [comment]
I don't have such a device for testing. But if this button is not visible, probably other stuff won't be visible either...

**Comment by woheller69** [comment]
you can add a location from GPS if allowed in settings.
If the button in the main activity is visible...
