### ISSUE TITLE
enhancement: Option to select perferred fuel type and option of sorting results by price or distance

### ISSUE THREAD

**Issue by lintux** [woheller69/spritpreise#2]
Hi,

my suggestion for the app would be to optionally enter a preferred fuel type and only show this one.
If this selected, then allow to sort results by distance.
For the Widget option to only show the cheapest preferred result.

BR
lintux

**Comment by lintux** [comment]
Thats why I mentioned it as optional for the start.
Could also be an option to be configured for multiple widgets.

**Comment by woheller69** [comment]
Please try. You can select "All" or one type like "E5" and you can set sort to price or dist.
"Price" will only be applied if a single type is selected. If "all" is selected it will always sort according to distance.

Remove .zip and install. If you have the version from F-Droid you have to uninstall first.
[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/8603663/app-release.apk.zip)

**Comment by lintux** [comment]
Good news .. 
Is that the 1.2 Version? If it will be released on F-Droid anyway, I would prefer to wait until the release.

**Comment by woheller69** [comment]
no. This might be a V1.3

**Comment by lintux** [comment]
I tried the previously attached version . It does not show any results regardless if the new settings are used or not.

**Comment by woheller69** [comment]
Then maybe you have to change the range? For me it works well

**Comment by lintux** [comment]
I used the same parameters as for the regular release ..

**Comment by woheller69** [comment]
Just uninstalled the app, downloaded from here, removed .zip, installed -> works well...
This app has a built-in API key btw.

**Comment by lintux** [comment]
Ah - I added my own API Key .. might that be the problem? I tried it twice now as well (with the same result), but always entered my own API Key

**Comment by woheller69** [comment]
Should not be a problem, as long as your key is correct

**Comment by lintux** [comment]
Ok, found the issue:
- own API works
- when initialized the "Sorte" Field in Settings is blank instead of "Alle" which ends up in finding no Locations at all

Now it works as I can see.

**Comment by woheller69** [comment]
ok great. I fixed the blank setting, but that was not the problem. I added an error message for possible API-key problem
