### ISSUE TITLE
allow larger search radius 

### ISSUE THREAD

**Issue by xandro0777** [woheller69/spritpreise#22]
... depending on some conditions:

* user enters own key
* lower update frequency

**Comment by woheller69** [comment]
I can increase to 25km which is the limit of the API

**Comment by xandro0777** [comment]
That would be perfectly fine. More would be rarely useful - the useful exception being search along a long travel route. This special case would be indeed very nice even if implemented only approximately using direction/distance. Should I open an issue for that?

**Comment by woheller69** [comment]
along a travel route will not be supported. you can add several locations along a route

**Comment by xandro0777** [comment]
Ok, in that case the 25 km search would be really nice.

**Comment by woheller69** [comment]
[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11069496/app-release.apk.zip)

you can try this.
Uninstall
Remove .zip
Install

**Comment by xandro0777** [comment]
Works fine. 

Next.. is there an option to hide closed stations? Should I open another issue for that?

**Comment by woheller69** [comment]
with option to hide closed stations:
[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11070833/app-release.apk.zip)

**Comment by xandro0777** [comment]
On March 26, 2023 5:23:46 AM UTC, woheller69 ***@***.***> wrote:
>with option to hide closed stations:
>[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11070833/app-release.apk.zip)

works nicely.

Next on my wishlist, would it be possible to display the "real" distance and direction from current/last established GPS location?  Apparently the API gives enough information, I can find reference to the Orthodrome formula implementation if that helps.. last done it on my Casio 602P;)

**Comment by woheller69** [comment]
For the real distance you would need routing.
The line of sight distance is shown if you use the widget with GPS

**Comment by xandro0777** [comment]
Ok, I did mean the line of sight aka Orthodrome. Would be nice to have that in the App as well.

**Comment by woheller69** [comment]
For max 25 km that is not relevant

**Comment by xandro0777** [comment]
On March 26, 2023 10:11:23 AM UTC, woheller69 ***@***.***> wrote:
>For max 25 km that is not relevant
>
#1 it is confusing if widget and app display a distance up to 25km different
#2 I may ask for the cheapest price within 25km of Holzkirchen either from Rosenheim, Munich or Starenberg which will make a difference

**Comment by woheller69** [comment]
Widget and app show the same distance

**Comment by xandro0777** [comment]
>Widget and app show the same distance

only the 'GPS tab" shows the same distance, all other show some other distance.

**Comment by woheller69** [comment]
they all show the distance from the selected location. If GPS is on the first Tab uses "your" position as location

**Comment by xandro0777** [comment]
I think it would be nice if all the tabs would behave the same because this confused me into thinking that they show the distance to the center of the search radius.

From a practical viewpoint, I have Holzkirchen predefined and it makes a big difference from which direction I approach it so in this case the sight of line distance would be much preferred over distance from the center of that place if doable.

**Comment by woheller69** [comment]
they behave all the same. It is the distance from the center or the search radius.
If you are in the center of the search radius it is in addition your distance to the station

**Comment by xandro0777** [comment]
It is entirely possible that a single gas station will appear in two or more tabs.. and will display different distance. It would appear to me that it would be more useful if it would display distance from current location in all tabs.

**Comment by woheller69** [comment]
this will not be changed
