### ISSUE TITLE
Eats battery 

### ISSUE THREAD

**Issue by xandro0777** [woheller69/spritpreise#24]
I have Radarweather and this App as widgets on the home screen, next to each other. Radarweather consumes around 0.55% battery, this one is competing for the first place with Firefox/Fennec which I use for TV and video streaming heavily.

I did watch that for a few days and made sure not to touch either widget for 24h, still the same result. Today gas prices is at 20%, the next telegram and fennec 13 and 12.

**Comment by xandro0777** [comment]
15 minutes update, sort by price, hide closed stations and no special other settings iirc

**Comment by woheller69** [comment]
that is a bug in Androids calculations

**Comment by xandro0777** [comment]
Quite possible, but why does it affect gas prices and not Radarweather?

**Comment by woheller69** [comment]
no idea, it is mainly the same app.

if you are using location in the widget and drive a lot the app updates data quite often

**Comment by woheller69** [comment]
but usually it does not do that while in sleep mode. Maybe your GPS is bad and consumes a lot...

**Comment by xandro0777** [comment]
I think I have same settings for both widgets but I am not sure Radarweather supports the continuous GPS update?

Didn't drive around on the weekend.

GPS is "bad" because I block AGPS internet lookup but used both Osmand and google maps and both show sub percent battery usage.

**Comment by xandro0777** [comment]
I did set both apps to update each 30 minutes to see what it does.

**Comment by woheller69** [comment]
that has no effect on the widget.

I have seen such numbers when using the widget as well, but the total consumption of the phone is almost the same.

It is just an attribution issue in Androids calculations.

**Comment by xandro0777** [comment]
I am inclined to believe that but it would be nicer if the attribution was more correct as is with Radarweather.

I will have a look with adb tonight, "top" is usually pretty reliable but only for the moment it runs, other ideas?

**Comment by woheller69** [comment]
probably Android will attribute the 20% to Radarweather if you remove gas prices.

Btw my omWeather app is better than RadarWeather...

**Comment by xandro0777** [comment]
On April 3, 2023 10:27:04 AM UTC, woheller69 ***@***.***> wrote:
>probably Android will attribute the 20% to Radarweather if you remove gas prices.

No, it never did.. I would have surely noticed and have installed gas prices only recently.

>Btw my omWeather app is better than RadarWeather...

Have seen it and installed but not yet replaced the widget. Thanks, will look more into it.

**Comment by xandro0777** [comment]
After installing omWeather the battery usage is split between those two so it is easier to miss among other apps  but  either of those is still attributed more about 15 times the battery usage as Radarweather. With adb top I was able to identify another horrendous CPUhog, lets see how the stats change.
