### ISSUE TITLE
Unclear when the last update was

### ISSUE THREAD

**Issue by mueller-ma** [woheller69/spritpreise#27]
**Describe the bug**
For me it's sometimes not clear when the last update was. The apps shows the text "last update (HH:MM)", but without displaying the date it could be the time from today or any other day.

**How to Reproduce**
1. Open the app and don't refresh manually

**Expected behavior**
Make the "last update" text dependent:
* If last update was less than a minute ago: Display "now"
* If it was today: Display time only (same as current behavior)
* If it wasn't today: Display time and date

**Comment by woheller69** [comment]
the longest update interval is 30min
I you open later than that it will immediately be updated
