### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by livodeu** [woheller69/spritpreise#3]
I'd suggest slight amendments:

1. Make it clearer that the fdroid version does NOT work without requesting an API key while the github version does.
2. I had trouble (or I thought that I had trouble) with starting the app for the first time because there were no locations present or selectable. Turned out that it apparently only took some time to load them. Maybe it's a good idea to give the user a clue what's happening.

**Comment by woheller69** [comment]
I added an additional remark regarding the F-Droid version.
Unfortunately F-Droid does not support the injection of secret credentials during build.

Regarding 2. 
For searching locations the app uses the Photon API which searches locations as you type.
There is no difference between first time or later.
