### ISSUE TITLE
[Feature request] Map only and colored icons

### ISSUE THREAD

**Issue by juup** [woheller69/spritpreise#30]
Thanks for your work.

Since #6 is already closed, I would like to ask for two improvements.

1) Display the map in full screen with the prices as small icons. (As seen on the screenshot in #6)

2) If no price icons are desired or as a general improvement it would help if the gas station icons are colored differently. E.g. like this:
- green / best price
- yellow / 1-2 cent more expensive than best price
- orange / 3-4 cents more expensive than best price
- Red the rest

**Comment by woheller69** [comment]
The osmdroid markers only support either text or icons.
And icon colors are used for open/closed.

But if your list is sorted by price just click on the first (cheapest) station and you will see a circle around it

**Comment by juup** [comment]
Thanks for your quick reply. 

I already know the function of the circle, but I don't find it very comfortable compared to an immediate classification by colors. 
What's wrong with extending the palette of colors? Closed gas stations are then gray or black?
And I don't understand the objection "only support either text or icons", because when selecting a gas station in the map, I also get a text (name and price) displayed and the icon remains.

What do you think about point 1), a full screen map?

**Comment by woheller69** [comment]
will increase the map to about 50% of screen height.
The popup window with price is only shown when an icon is clicked. The marker itself only supports icon or text.

**Comment by woheller69** [comment]
[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11441184/app-release.apk.zip)

**Comment by juup** [comment]
It feels like we are talking past each other. 
On the screenshot in #6 you can see which view is very helpful. I wrote "icons with text" and meant your popup windows for all stations.

It's your app and your decision how it should look like. If 50% map is your ideal, okay. 
Full screen (at least as an option) and the ability to see essential info directly in the map (via colors or price display) are just a user request.
