### ISSUE TITLE
Problem with Avanti stations

### ISSUE THREAD

**Issue by xandro0777** [woheller69/spritpreise#36]
Most or all of them suddenly appear twice in the list - with slightly different name "avanti" vs "AVANTI" and different prices. Apparently the name changed somewhere and the old entry got stuck and is never updated.

Really bad because they display unrealistically low prices.

**Comment by woheller69** [comment]
you can try to notify Tankerkönig ...

**Comment by xandro0777** [comment]
That is a possibility, but should there bea  sanity check to discard entries that weren't changed a few days? Interesting things also happen if a station closes.

**Comment by woheller69** [comment]
No, checks make no sense in the app. The source must be correct

**Comment by xandro0777** [comment]
Having a blacklist feature would be another possibility

**Comment by xandro0777** [comment]
The widget is displaying the same stuck entry since days now.
