### ISSUE TITLE
Fehler beim Abrufen der Daten

### ISSUE THREAD

**Issue by toas-koas** [woheller69/spritpreise#37]
**Describe the bug**
Beim aufrufen eines Ortes erscheint die Fehlermeldung

**How to Reproduce**

- Menü
- Spritpreise

**Screenshots**

**Environment (please complete the following information):**
 - App Version 2.3
 - Android version: 13 DivestOS
 - Device: Google Pixel 2XL

**Comment by woheller69** [comment]
Maybe a problem with your internet connection. Does that happen when you press the refresh button?

**Comment by toas-koas** [comment]
Sorry. I don't confirmed my API key. Now it works
