### ISSUE TITLE
[Improvement] Radius setting for each Location + Coordinates

### ISSUE THREAD

**Issue by mar565** [woheller69/spritpreise#38]
Hello,
First of all thank you for the great app. Im just missing some fine tuning options:
-ability to set radius for each location
-ability to set coordinates as a location, to bei able to center the radius according to my local cirumstances.

The colour coded price mentioned in another issue a feuture id like to have.

**Comment by woheller69** [comment]
You can allow GPS to set your current coordinates as location.

**Comment by mar565** [comment]
Ok, this works. Thank you. What about the radius setting?

Detailed workaround:
-go to the desired location or fake your gps
-move the tile with your current location to another position in the list. Now its saved and can be renamed. The tile that is now in the first position will be overwritten with the current location.

**Comment by woheller69** [comment]
if you use the widget you can let the widget update the location in the first tab automatically as you drive.

A  location depedent radius just makes things more complicated, I do not plan to implement that.

**Comment by mar565** [comment]
I dont think that you get what Im actually suggesting.
The requst for setting a location by coordinates is to cover the most significant service stations arround my exact home and work adress. This can be done by my workaround.

The different radius ist because while traveling (moving mode/Location by GPS) I just want to see the nearest stations.
If I want to check the usual stations I go to near my home (manually selecting the saved location in the app) I would prefere to have a larger area covered.
