### ISSUE TITLE
[Improvement] Layout in landscape mode

### ISSUE THREAD

**Issue by d1vzero** [woheller69/spritpreise#39]
Hi,
first of all thank you for the excellent app. I am using it on a Android based head unit in a car. Naturally in contrast to smart phones it's screen is oriented in landscape mode, which makes it hard to grasp the information if the screen is split in upper part for the map and lower part for the pricing table.
Hence I request for a side-by-side layout for landscape mode.

Best regards and thank you in advance.

**Comment by woheller69** [comment]
Good idea. Here it is, please try:

-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/12460335/app-release.apk.zip)

**Comment by d1vzero** [comment]
That was fast....
So far I was able to just test on my smartphone. Works well.
I will test on the cars head unit as well and will report here. However I do not expect any issues there.

**Comment by d1vzero** [comment]
I was able to test in the car now. Works well.
The only unfortunate point was, that the app crashed when I tried to add a new location. The dialog for the selection of the location did not appear. On my smartphone however it worked.

**Comment by woheller69** [comment]
Did the app crash or did the dialog not appear?
That has not been changed. Which Android version?
Can you use GPS in the app?

**Comment by d1vzero** [comment]
The Dialog did mit appear. Instead the App crashed. GPS was Wirkung well.
It's Android 10

I also cleared cache and app data again without any success.

**Comment by woheller69** [comment]
when did it crash? When you pressed the button at the bottom right in the manage locations activity?

**Comment by d1vzero** [comment]
Yes, exactly Ehen I pushed the button. Before the Dialog could appear, the app crashed.

**Comment by woheller69** [comment]
Interesting, I am using this in 4 apps and nobody ever had a problem so far...

Can you please try this?
Does it show a message "Language:..."?
Does it still crash?

[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/12471916/app-release.apk.zip)

**Comment by d1vzero** [comment]
I will most likely be able to try in the evening. In the meantime I tried the new version on my smartphone again. Here I do see the small popup with the language. It is the same type of message window which occurs to show error messages, right? Like when there is no internet connection.  I have (using the girst version provided by you) so far not seen this type of message on the cars head unit. So this might be the right direction. On the head unit the internet connection is not rock stable. So I can imagine it ran out of a proper connection (or high latency). This triggered an error in your app but was not able yo show the message and crashed.
I will try and report here.

**Comment by woheller69** [comment]
no, it is not an internet connection issue. I checked the code and found, that a crash can happen if the app does not find a language setting, which should usually never be the case. If it finds one, it will show it in this test version

**Comment by d1vzero** [comment]
OK, with your test version no language message shows up on the screen of the cats head unit. Instead the app crashes like before.
To be sure I also installed the latest version from the G-Dtoid again. Same result, although I thought it used to be different bit I guee my mind is fooling me.

**Comment by woheller69** [comment]
Does the crash still happen with V2.4 from F-Droid?

**Comment by d1vzero** [comment]
I checked but unfortunately it still crashes. Bit crash may not be the correct word. It now just switches back to the last screen , means the app still executes.
However, landscape mode is fine. So let's close this issue and maybe open up another for the "app crash" when choosing the location.
Thanks a lot.

**Comment by woheller69** [comment]
I have no further idea at the moment why it still crashes. A logcat might help. No idea if you can get one from that device

**Comment by d1vzero** [comment]
Well, sure I am willing to try. How can I obtain that log?

**Comment by woheller69** [comment]
you need a computer, USB cable, and the tool adb

https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/

**Comment by d1vzero** [comment]
OK, thanks. I will give it a try, but it will take some time.

**Comment by woheller69** [comment]
No problem, it seems you are the only user with that issue...
