### ISSUE TITLE
Frage: Benzinpreishistorie

### ISSUE THREAD

**Issue by michaelof** [woheller69/spritpreise#48]
Hallo,

erst einmal ganz vielen Dank für diese nette und nützliche App!!!

Ich habe eine generelle Frage: Zumindest bei uns pendeln die Spritpreise meistens bzw. zumindest zeitlang recht wiederkehrend. Also zB morgens am teuersten, spätabends am billigsten, nachts, wenn die Nonames zu haben, nochmals teurer.
Was ich daher extrem nützlich fände: Meistens kann ich das Tanken etwas schieben, muss selten sofort tanken. Oder könnte früher als nötig tanken, weil gerade besonders billig. Dazu wäre es toll, wenn es "historische" Preis gebe. ZB die der letzten 24/48 oder sogar 72h, um zusätzlich einen Auf- oder Abwärtstrend erkennen zu können.

Da ich keine einzige App kenne, die das bietet, Eure nicht, die ADAC App nicht, bin ich mir nicht sicher:
- Bin ich der Einzige, der sowas gut fände?
- oder geht das lizenzrechtlich nicht?
- Oder macht das keiner, weil dann statt ad hoc API Abfragen die historischen Daten gespeichert werden müssten?

Über Feedback würde ich mich freuen. Und sollte es an Aufwand liegen, dass es keiner macht, werde ich wahrscheinlich über den API Key selber was ganz schlankes basteln, tatsächlich geht es ja in meinem Fall um max. 5-10 Tankstellen in der Umgebung.

Die Amplituden sind mit mehr als 10ct/l aber einfach elend groß :)

**Comment by woheller69** [comment]
Dafür müsste man ständig die Daten abrufen, was Tankerkönig nicht mag...
Will nicht, dass mein Key gesperrt wird...

**Comment by michaelof** [comment]
Ja, sowas hab ich vermutet, nachvollziehbar :)

Tankerkönig hat aber genau das, was ich suche, unter https://dev.azure.com/tankerkoenig/_git/tankerkoenig-data gibts sauber nach Jahr/Monat/Tag abgelegt tgl. aktualisierte Daten. Neue Deltas dann zB  per git pull  automatisch. Ich werde mir für die Historie was einfaches in LibreOffice Calc basteln.

DANKE also für Antwort und Tipp!
