### ISSUE TITLE
Possibility to add Spain

### ISSUE THREAD

**Issue by Pablohn26** [woheller69/spritpreise#49]
**Describe the bug**
It seems this app only support Germany places. Is it possible to add Spain? The API is here: 
https://geoportalgasolineras.es/geoportal-instalaciones/DescargarFicheros

**How to Reproduce**
1. Go to locations
2. Search any place in Spain

**Expected behavior**
Get prices from Spain

**Screenshots**
Not needed

**Environment (please complete the following information):**
 - App version: Not needed
 - Android version: Not needed
 - Device: Not needed

This could be a sponsored feature request (please contact me if you are interested)

**Comment by woheller69** [comment]
Sorry, but I have no plan to add other countries for this app.
But maybe someone else wants to fork an implement it.
