### ISSUE TITLE
Dark mode - font color contrast too low

### ISSUE THREAD

**Issue by BluePixel4k** [woheller69/spritpreise#5]
**Describe the bug**
If the Dark Mode is activated, then the contrast of the font color is too low. This makes it difficult to read the text/prices quickly.
The gray shade is too dark.

**How to Reproduce**
1. Go to 'Settings'
2. Click on 'Android 10+ Dark Mode'
3. View gas stations

**Screenshots**
<img src="https://user-images.githubusercontent.com/77979781/170481311-b1774b01-5303-4678-a84c-fc1e1db57ff6.png" width="300" />

**Environment (please complete the following information):**
 - App version: v1.2
 - Android version: 12.1
 - Device: Google Pixel 5

**Comment by woheller69** [comment]
will slightly increase contrast in next release

**Comment by BluePixel4k** [comment]
Thank you 👍🏼

**Comment by woheller69** [comment]
-> V1.4
