### ISSUE TITLE
[Feature request] Map with gas stations and their prices

### ISSUE THREAD

**Issue by BluePixel4k** [woheller69/spritpreise#6]
Certainly this function is complex to implement or it is not even possible with the Tankerkönig API, but an overview map with the gas stations and their prices would be a great feature.

For example, like this:
<img src="https://user-images.githubusercontent.com/77979781/170687210-8f1c96e1-8ed2-4d5d-8b4b-97f95b4a4beb.png" width="300" />

But with OpenStreetMap as you have also implemented in your weather app.

**Comment by woheller69** [comment]
I won't implement that either. But you can click on a station and open you favorite maps app. And start navigation there

**Comment by woheller69** [comment]
Please try this. The map shows the location of the gas stations. When you click on them you will see brand and prices.
The map can be switched off in settings.

- Uninstall (if F-Droid version is installed)
- Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11312272/app-release.apk.zip)

**Comment by woheller69** [comment]
Another bugfix: list was cut off at bottom
[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11320010/app-release.apk.zip)

**Comment by woheller69** [comment]
better solution:
[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/11321162/app-release.apk.zip)
