### ISSUE TITLE
[Feature request] Price history

### ISSUE THREAD

**Issue by BluePixel4k** [woheller69/spritpreise#7]
If the Tankerkönig API allows it, a price history of the single gas stations would be a practical function to be able to estimate how the price could still change on the day and how the trend looked like over the last day/weeks.

For example, like this:
<img src="https://user-images.githubusercontent.com/77979781/170688444-41877d7e-24a3-4a30-b0ce-6be9df3f0640.png" width="300" />

**Comment by woheller69** [comment]
not possible with free Tankerkönig API

**Comment by BluePixel4k** [comment]
Okay sad, do you have any idea how expensive the Pro version is? At least I can't find anything concrete on their website.
Such costs are of course not so great for an open source app, unless the users who want it pay for it.

**Comment by woheller69** [comment]
no idea, probably only for large customers

**Comment by FlRedder** [comment]
I'm not an Android expert, but wouldn't it be possible to configure a background task running e.g. every 5...15mins, accessing the Tankerkönig API and storing the history for a selected station locally on your phone? To limit required storage space you could limit the history length to a certain interval and show the approximately required space?

**Comment by woheller69** [comment]
"Regelmäßige, nicht explizit vom User initiierte Requests sind zu vermeiden"

https://creativecommons.tankerkoenig.de/
-> Terms

**Comment by FlRedder** [comment]
@woheller69 Thanks for the quick response. I understand the need for limiting reoccurring server requests as stated in the terms. However I feel the server load should not increase too much if you limit the number of stations "subscribed to" to e.g. 1...3 per API key and request intervals to 15mins.

Nevertheless, I'm aware that the number of requests scales with the number of users.

Anyway, I just realized they added a GIT repo for daily historic data [here](https://dev.azure.com/tankerkoenig/_git/tankerkoenig-data). Would it be an option to include this in the app?

**Comment by woheller69** [comment]
the download is 50 GB ...

**Comment by FlRedder** [comment]
@woheller69 Sure, for the whole repo. But one day data for all the stations is about 28MB. That's still quite some data and you'd have to download first and then filter by station id. Hence in theory historic data is available. However, I feel without a proper api to the data, the overhead is significant.

**Comment by RedCommander735** [comment]
Another idea for this would be to store the prices whenever you get them anyway for displaying in app. Maybe averaging them with already stored prices for that time +-15min/30min from the last week or so and using that for an "average price history".
