### ISSUE TITLE
Enhancement: Update GPS location when manually refreshing in the app

### ISSUE THREAD

**Issue by manuquadrat** [woheller69/spritpreise#9]
Hi,

I recently noticed that the GPS location only updates when you refresh via the widget. It would be great if you could add an option that the location also updates when you refresh in the app itself (or even make this default behaviour), as some people may prefer to not use a widget.

**Comment by woheller69** [comment]
acquiring location can take a while, depending on your phone.
That is handled in background by the widget.

**Comment by manuquadrat** [comment]
I think there might be a little misunderstanding. What I meant was that it would be great if there was an option to update the GPS location without a widget.

**Comment by woheller69** [comment]
I know, but the widget is needed to update location in background. Otherwise you would press refresh in the app and then have to wait a few minutes until there is a GPS fix.

**Comment by jenslody** [comment]
I would also like to have the option to refresh location without the widget.
I know, that it might take some time to get a fix, but that's not an issue for me and you can notify the user about this as long as the app waits for a fix.
By the way it usually takes some seconds before I get a fix after opening Sat-Stat, even indoor.

**Comment by woheller69** [comment]
please try. If GPS is allowed in settings there is a location icon next to the refresh button.
When clicked it will blink until a new location is found and update the first TAB.

Remove .zip and install.

[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/9099187/app-release.apk.zip)

**Comment by woheller69** [comment]
another update

Remove .zip and install.

[app-release.apk.zip](https://github.com/woheller69/spritpreise/files/9099566/app-release.apk.zip)

**Comment by manuquadrat** [comment]
Hi,
thank you for the update. I installed the apk from your second post and it did work well, but I did not try it extensively yet.

**Comment by jenslody** [comment]
Sorry for the late reply, I'm not at home.
First test looks good.
One small thing: it might be good to jump to the first tab, if the gps refresh-button is clicked from another tab.

**Comment by woheller69** [comment]
depending on  your phone it can take minutes until a new location is found. So I don't think I will jump to the first tab when clicked from another tab

**Comment by woheller69** [comment]
->V1.4
